# Site settings
title: Bavel Wiki
email: contact@bavel.io
description: > # this means to ignore newlines until "baseurl:"
  Bavel SDK documentation and general topics regarding implementaion, reported data,
  FAQ and others.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wiki.bavel.io" # the base hostname & protocol for your site
twitter_username: jekyllrb

# Build settings
markdown: kramdown
